config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
    root to: "home#index"
    resources :images
 get 'probar', to: 'control#saludos'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
    mount_uploader :picture, PictureUploader

    validates :description, presence: true

    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :images
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :configure_devise_params, if: :devise_controller?
    def configure_devise_params
        devise_parameter_sanitizer.permit(:sign_up) do |user|
            user.permit(:name, :email, :password, :password_confirmation)
        end    
    end
end

app/controllers/control_controller.rb
class ControlController < ApplicationController
    def saludos
        @myname = 'juan pablo'
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
    @images = Image.paginate(:page => params[:page], :per_page => 12).order(id: :desc)
                .where user_id: current_user.id
    end
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
    before_action :set_image, only: [:show, :edit, :update, :destroy]
    def index
        @images = Image.where user_id: current_user.id
    end
    def new
        @image = Image.new
    end
    def create
        @image = current_user.images.new image_params
        #render plain: params[:image].inspect # nos renderiza el codigo ingresado
        #@image = Image.new image_params
       if @image.save 
       return redirect_to images_path 
       end
       render :new
    end
    
    def show
    end

    def edit 
    end

    def update 
        @image.update image_params
        redirect_to @image
    end

    def destroy 
        @image.destroy
        redirect_to images_path
    end

    private 
    def image_params
        params.require(:image).permit:description, :picture
    end

    def set_image
        @image = Image.find params[:id]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/control_helper.rb
module ControlHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/control/saludos.html.erb
<h1> hola desde control <%= @myname %> </h1>

app/views/home/index.html.erb
<% if user_signed_in? %> 
    <div class="row">
        <div class="col-4">

        </div>
          <div class="col-8">
          <h1> <%= current_user.name %> </h1>
             <div>
             <ul class="nav">
                    <li class="margin-right">
                        <p> <strong> <%= @images.count %>  </strong>  publicaciones </p>
                    </li>
                     <li class="margin-right">
                        <p> <strong> 300 </strong> seguidores </p>
                    </li>
                     <li class="margin-right">
                        <p> <strong> 100 </strong> seguidos </p>
                    </li>
             </ul>
            </div>
        </div>
    </div>
    
    
    <div class="row">
        <%= render @images %>
    </div>
    <%= will_paginate @images %>

<% else %> 
<h1> Railsgram </h1>
<% end %> 

app/views/images/_form.html.erb
    <% if @image.errors.any?%>
    <div class= "alert alert-danger">
    <h4 class= "alert-heading"> oh no!</h4>
    <p> ha ocurrido un error </p>
    </div>
    <% end %>

    <div class="form-group"> 
    <%= form_for @image do |f|  %>
        <%= f.label :description %> <br>
        <%= f.text_field :description, class: 'form-control' %>  
        <%- if @image.errors[:description].any?%>
        <span class="badge badge-pill badge-danger"> 
        <%= @image.errors[:description].first %>
        </span>
        <% end %>
        <br>
        <%= f.label :picture %> <br>
        <%= f.file_field :picture  %>   
        <br>
        <%= f.submit 'Enviar', :class => 'btn btn-primary'%>
  
    <% end %>
    </div>

app/views/images/_image.html.erb
<div class="col-4">
    <figure class="figure">
        <%= image_tag image.picture.medium.url, class: 'figure-img img-fluid rounded' %>
        <figcaption class="figure-caption"> 
        <%= image.description %> 
        <%= link_to 'Edit', edit_image_path(image) %>
        <%= link_to 'eliminar', image, method: :delete, data: {confirm: 'estas seguro?'} %>
        <br>
        </figcaption>
    </figure>
</div>

app/views/images/edit.html.erb
<div class="container"> 
    <p> editar imagen </p>

    <%= render 'form'%>
</div>

app/views/images/index.html.erb
<div class="container">
    <div class="row">
    <%= render @images %>
    </div>
</div>

app/views/images/new.html.erb
<div class="container"> 
<%= render 'form'%>
</div>

app/views/images/show.html.erb
<%= image_tag @image.picture.medium.url, class: 'figure-img img-fluid rounded' %>
<%=  @image.description %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railsgram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <ul class= "nav justify-content-end">
    <%- if user_signed_in? %>
    <li class="nav-item">
    <%= link_to 'salir', destroy_user_session_path, method: :delete,
    class: "nav-link" %>
    <%= link_to 'crear imagen', new_image_path,
    class: "nav-link" %>
    </li>
   
    <% else %>

    <li class="nav-item">
    <%= link_to 'Iniciar sesion', new_user_session_path,
    class: "nav-link"%>
    </li>

    <li class="nav-item">
    <%= link_to 'Registrarme', new_user_registration_path,
    class: "nav-link"%>
    </li>
  <% end %>
  </ul>
  <div class="container">
        <p class="notice"><%= notice %></p>
         <p class="alert"><%= alert %></p>

    <%= yield %>
    </div>
  </body>
</html>